# Generated by Django 4.0.6 on 2022-08-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='idiom',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('fr', 'French'), ('ja', 'Japanese'), ('pt-BR', 'Portuguese'), ('pl', 'Poland'), ('ru-RU', 'Russian')], default='en-US', max_length=6),
        ),
    ]
