# Generated by Django 4.0.6 on 2023-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_newuser_idiom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='idiom',
            field=models.CharField(choices=[('de', 'German'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('it', 'Italian'), ('ru', 'Russian')], default='en-US', max_length=6),
        ),
    ]
