# Generated by Django 4.0.5 on 2022-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='idiom',
            field=models.CharField(default='en-US', max_length=15),
        ),
    ]
