// All the Types in a single const action. Actions need to be called actions.<<Name>>
export const actions = {
  // Users
  LOGIN_SUCCESS : 'LOGIN_SUCCESS',
  LOGIN_FAIL : 'LOGIN_FAIL',
  SIGNUP_SUCCESS : 'SIGNUP_SUCCESS',
  SIGNUP_FAIL : 'SIGNUP_FAIL',
  ACTIVATION_SUCCESS : 'ACTIVATION_SUCCESS',
  ACTIVATION_FAIL : 'ACTIVATION_FAIL',
  USER_LOADED_SUCCESS : 'USER_LOADED_SUCCESS',
  USER_LOADED_FAIL : 'USER_LOADED_FAIL',
  AUTHENTICATED_SUCCESS : 'AUTHENTICATED_SUCCESS',
  AUTHENTICATED_FAIL : 'AUTHENTICATED_FAIL',
  PASSWORD_RESET_FAIL : 'PASSWORD_RESET_FAIL',
  PASSWORD_RESET_SUCCESS : 'PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_CONFIRM_FAIL : 'PASSWORD_RESET_CONFIRM_FAIL',
  PASSWORD_RESET_CONFIRM_SUCCESS : 'PASSWORD_RESET_CONFIRM_SUCCESS',
  GOOGLE_AUTH_SUCCESS : 'GOOGLE_AUTH_SUCCESS',
  GOOGLE_AUTH_FAIL : 'GOOGLE_AUTH_FAIL',
  FACEBOOK_AUTH_SUCCESS : 'FACEBOOK_AUTH_SUCCESS',
  FACEBOOK_AUTH_FAIL : 'FACEBOOK_AUTH_FAIL',
  LOGOUT : 'LOGOUT',
  // Tasks
  ADD_TASK:'ADD_TASK',
  REMOVE_TASK:'REMOVE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  ADD_ERROR: 'ADD_ERROR',
  DELETE_ERROR: 'DELETE_ERROR',
  UPDATE_ERROR: 'UPDATE_ERROR',
  On_SUCCESS:'OnSuccess',
  On_FAILURE:'OnFailure',
  //Blogs
  SET_COUNT:'SET_COUNT',
  FIELDS: 'FIELDS',
  //Counter
  INCREMENT:'INCREMENT',
  DECREMENT:'DECREMENT',
  //Cart
  SHOW_HIDE_CART: "SHOW_HIDE_CART",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
  UPDATE_CART: "UPDATE_CART",
  //Categories
  TOGGLE_CATEGORY_SELECTION:"TOGGLE_CATEGORY_SELECTION"
};