# Generated by Django 4.0.6 on 2023-02-19 16:26

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=2, default=39.99, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo2', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo3', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo4', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo5', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo6', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo7', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo8', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('photo9', models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('video', models.FileField(blank=True, null=True, upload_to=products.models.upload_image_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
