# Generated by Django 4.0.6 on 2023-03-05 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_upload_productimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='photo9',
        ),
    ]
