# Generated by Django 4.0.6 on 2023-04-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_promotions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
